# -*- coding: utf-8 -*-
"""NLP3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Ao0xd_lS-W5UZNxGvFShrGtMrTy7vO5
"""

from rnnmorph.predictor import RNNMorphPredictor
import nltk
from nltk.tokenize import word_tokenize

predictor = RNNMorphPredictor(language='ru')
nltk.download('punkt')

text = open('/content/Text.txt', 'r', encoding='utf-8')
text = text.read()
print(text)

def get_tags(tag):
  tags = {}
  parts = tag.split('|')
  for i in parts:
    tag = i.split('=')
    tags[tag[0]] = tag[1]
  return tags

words = word_tokenize(text)
res = predictor.predict(words)

for i in range(len(words) - 1):
  predict_first = res[i]
  predict_second = res[i + 1]
  if ((predict_first.pos == 'NOUN') | (predict_first.pos == 'ADJ')) & ((predict_second.pos == 'NOUN') | (predict_second.pos == 'ADJ')):
    tags_first = get_tags(predict_first.tag)
    tags_second = get_tags(predict_second.tag)
    if ('Gender' in tags_first) & ('Gender' in tags_second):
      if tags_first['Case'] == tags_second['Case']:
        if tags_first['Gender'] == tags_second['Gender']:
          if tags_first['Number'] == tags_second['Number']:
            print(predict_first.normal_form, predict_second.normal_form)